# Generated by Django 5.1.6 on 2025-09-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_bio_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='currency_symbol',
            field=models.CharField(default='₱', max_length=5),
        ),
    ]
