# Generated by Django 5.1.6 on 2025-09-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit - Auto-generated if not provided', max_length=50, unique=True),
        ),
    ]
