# Generated by Django 5.1.6 on 2025-09-14 15:00

import pos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image (Max: 5MB, Recommended: 300x300px)', null=True, upload_to='products/', validators=[pos.validators.validate_image_file]),
        ),
    ]
